updated sdl2 to 2.0.12

diff --git a/package/sdl2/patch1.patch b/package/sdl2/patch1.patch
--- a/package/sdl2/patch1.patch
+++ b/package/sdl2/patch1.patch
@@ -1,14 +1,14 @@
---- a/configure	2017-09-22 20:25:52.000000000 +0200
-+++ b/configure	2021-06-04 20:08:37.616000961 +0200
-@@ -848,6 +848,7 @@
- enable_video_cocoa
+--- a/configure	2019-07-23 21:41:00.000000000 +0200
++++ b/configure 2021-06-04 23:49:15.191268035 +0200
+@@ -872,6 +872,7 @@
+ enable_render_metal
  enable_video_directfb
  enable_directfb_shared
 +enable_video_fbdev
  enable_video_kmsdrm
  enable_kmsdrm_shared
  enable_video_dummy
-@@ -1597,6 +1598,7 @@
+@@ -1651,6 +1652,7 @@
    --enable-video-directfb use DirectFB video driver [[default=no]]
    --enable-directfb-shared
                            dynamically load directfb support [[default=yes]]
@@ -16,10 +16,11 @@
    --enable-video-kmsdrm   use KMSDRM video driver [[default=no]]
    --enable-kmsdrm-shared  dynamically load kmsdrm support [[default=yes]]
    --enable-video-dummy    use dummy video driver [[default=yes]]
-@@ -21384,6 +21386,26 @@
+@@ -21732,6 +21734,26 @@
+         fi
      fi
  }
- 
++ 
 +CheckFBDEV()
 +{
 +if test x$ARCH = xlinux -a x$enable_video = xyes; then
@@ -39,20 +40,54 @@
 +		fi
 +	fi
 +}
-+
+ 
  CheckKMSDRM()
  {
-     # Check whether --enable-video-kmsdrm was given.
-@@ -21400,7 +21422,7 @@
-         libgbm_avail=no
- 
-         LIBDRM_REQUIRED_VERSION=2.4.46
--        LIBGBM_REQUIRED_VERSION=9.0.0
-+        LIBGBM_REQUIRED_VERSION=2.0.0
- 
-         # Extract the first word of "pkg-config", so it can be a program name with args.
- set dummy pkg-config; ac_word=$2
-@@ -23766,6 +23788,7 @@
+@@ -21824,12 +21846,12 @@
+     pkg_cv_LIBGBM_CFLAGS="$LIBGBM_CFLAGS"
+  elif test -n "$PKG_CONFIG"; then
+     if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gbm >= 9.0.0\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "gbm >= 9.0.0") 2>&5
++    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gbm >= 2.0.0\""; } >&5
++  ($PKG_CONFIG --exists --print-errors "gbm >= 2.0.0") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   test $ac_status = 0; }; then
+-  pkg_cv_LIBGBM_CFLAGS=`$PKG_CONFIG --cflags "gbm >= 9.0.0" 2>/dev/null`
++  pkg_cv_LIBGBM_CFLAGS=`$PKG_CONFIG --cflags "gbm >= 2.0.0" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -21840,12 +21862,12 @@
+     pkg_cv_LIBGBM_LIBS="$LIBGBM_LIBS"
+  elif test -n "$PKG_CONFIG"; then
+     if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gbm >= 9.0.0\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "gbm >= 9.0.0") 2>&5
++    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gbm >= 2.0.0\""; } >&5
++  ($PKG_CONFIG --exists --print-errors "gbm >= 2.0.0") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   test $ac_status = 0; }; then
+-  pkg_cv_LIBGBM_LIBS=`$PKG_CONFIG --libs "gbm >= 9.0.0" 2>/dev/null`
++  pkg_cv_LIBGBM_LIBS=`$PKG_CONFIG --libs "gbm >= 2.0.0" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -21865,9 +21887,9 @@
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        LIBGBM_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "gbm >= 9.0.0" 2>&1`
++	        LIBGBM_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "gbm >= 2.0.0" 2>&1`
+         else
+-	        LIBGBM_PKG_ERRORS=`$PKG_CONFIG --print-errors "gbm >= 9.0.0" 2>&1`
++	        LIBGBM_PKG_ERRORS=`$PKG_CONFIG --print-errors "gbm >= 2.0.0" 2>&1`
+         fi
+ 	# Put the nasty error message in config.log where it belongs
+ 	echo "$LIBGBM_PKG_ERRORS" >&5
+@@ -24459,6 +24481,7 @@
          CheckRPI
          CheckX11
          CheckDirectFB
@@ -60,7 +95,7 @@
          CheckKMSDRM
          CheckOpenGLX11
          CheckOpenGLESX11
-@@ -23918,6 +23941,11 @@
+@@ -24632,6 +24655,11 @@
          if test x$use_input_events = xyes; then
              SOURCES="$SOURCES $srcdir/src/core/linux/SDL_evdev*.c"
          fi
@@ -70,5 +105,5 @@
 +			$as_echo "#define SDL_VIDEO_DRIVER_FB 1" >>confdefs.h
 +		fi
          # Set up other core UNIX files
+         SOURCES="$SOURCES $srcdir/src/core/linux/SDL_threadprio.c"
          SOURCES="$SOURCES $srcdir/src/core/unix/*.c"
-         ;;
